feat: council arbitrator
defi-wonderland/EBO-core pull request #10
Opened 2024-08-16 03:37 UTC by 0xJabberwock

# 🤖 Linear

Closes GRT-47

2024-08-16 17:31 UTC, 0xShaito requested changes

2024-08-16 17:31 UTC, 0xShaito commented on src/contracts/CouncilArbitrator.sol
> +    // TODO: Emit event with params? Save params locally?
I would emit event and save params locally to validate the call in resolveDispute and see that the disputeId is correct

2024-08-16 17:31 UTC, 0xShaito commented on src/contracts/CouncilArbitrator.sol
> +    // TODO: Provide or fetch params?
We can save them from the call to resolve

2024-08-16 17:31 UTC, 0xShaito commented on src/contracts/CouncilArbitrator.sol
> +    // TODO: Emit event with params? Save params locally?
We need to also check that the _dispute + _response + _dispute is a valid combo

2024-08-16 18:05 UTC, 0xShaito commented on src/contracts/CouncilArbitrator.sol
> +    // TODO: Emit event with params? Save params locally?
disputeId -> _request, _response, _dispute

2024-08-16 18:11 UTC, 0xShaito commented on src/contracts/CouncilArbitrator.sol
> +    // TODO: Emit event with params? Save params locally?
Emit event + save params locally disputeId -> _request, _response, _dispute

2024-08-19 22:33 UTC, 0xShaito approved these changes

2024-08-19 23:15 UTC, ashitakah approved these changes

2024-08-19 23:15 UTC, merged