refactor: integration create request
defi-wonderland/EBO-core pull request #11
Opened 2024-08-16 14:54 UTC by ashitakah

- Improving the create request function and the integration test.

2024-08-19 10:48 UTC, 0xShaito requested changes

2024-08-19 10:48 UTC, 0xShaito commented on src/contracts/EBORequestCreator.sol
> +          IEBORequestModule(_requestData.requestModule).decodeRequestData(_requestData.requestModuleData);
Decode it outside of the for loop

2024-08-19 10:48 UTC, 0xShaito commented on src/contracts/EBORequestCreator.sol
> +    // NOTE: SHOULD WE CREATE IN STORAGE THAT STRUCT TO AVOID ENCODE AND DECODE SEVERAL TIMES?
How can we do it? We would kinda still need to decode and encode multiple times right? Unless we save both encoded and decoded data. I worry more about the external call to do `decodeRequestData` but I don't think it's too bad tbh

2024-08-19 10:48 UTC, 0xShaito commented on src/contracts/EBORequestModule.sol
> +import {IAccountingExtension, IEBORequestModule} from 'interfaces/IEBORequestModule.sol';
Unused

2024-08-19 10:48 UTC, 0xShaito commented on test/integration/arbitrum/IntegrationBase.sol
> +    _eboRequestModule = new EBORequestModule(_oracle, _eboRequestCreator, _arbitrator, _council);
Can you precompute the eboRequestCreator

2024-08-19 10:48 UTC, 0xShaito commented on test/unit/EBORequestCreator.t.sol
> +  // NOTE: IF WE USE THIS TEST, WE HAVE TO CHANGE THE SETTINGS TO USE --VIA-IR BECAUSE WE HAVE TO CREATE A LOT OF VARIABLES
Don't use NOTE, use TODO so we can search it easily

2024-08-19 10:50 UTC, 0xShaito commented on test/integration/arbitrum/CreateRequest.t.sol
> +    assertNotEq(_eboRequestCreator.requestIdPerChainAndEpoch('chainId1', _currentEpoch), bytes32(0));
Check that the oracle has been sent the correct parameters and that the requestId actually exists in the oracle

2024-08-19 23:22 UTC, ashitakah commented on src/contracts/EBORequestCreator.sol
> +          IEBORequestModule(_requestData.requestModule).decodeRequestData(_requestData.requestModuleData);
👍

2024-08-19 23:22 UTC, ashitakah commented on src/contracts/EBORequestCreator.sol
> +    // NOTE: SHOULD WE CREATE IN STORAGE THAT STRUCT TO AVOID ENCODE AND DECODE SEVERAL TIMES?
👍

2024-08-19 23:23 UTC, ashitakah commented on src/contracts/EBORequestModule.sol
> +import {IAccountingExtension, IEBORequestModule} from 'interfaces/IEBORequestModule.sol';
👍

2024-08-19 23:32 UTC, ashitakah commented on test/integration/arbitrum/IntegrationBase.sol
> +    _eboRequestModule = new EBORequestModule(_oracle, _eboRequestCreator, _arbitrator, _council);
Why we want this? Also you need the params for precompute and maybe the requestData change

2024-08-19 23:32 UTC, ashitakah commented on test/unit/EBORequestCreator.t.sol
> +  // NOTE: IF WE USE THIS TEST, WE HAVE TO CHANGE THE SETTINGS TO USE --VIA-IR BECAUSE WE HAVE TO CREATE A LOT OF VARIABLES
👍

2024-08-20 00:09 UTC, ashitakah commented on test/integration/arbitrum/CreateRequest.t.sol
> +    assertNotEq(_eboRequestCreator.requestIdPerChainAndEpoch('chainId1', _currentEpoch), bytes32(0));
👍

2024-08-20 00:26 UTC, 0xShaito commented on test/integration/arbitrum/IntegrationBase.sol
> +    _eboRequestModule = new EBORequestModule(_oracle, _eboRequestCreator, _arbitrator, _council);
To not have to change the address manually in the next transaction by the council. When deploying we will be precomputing as we don't want to make the council make the change or have to set stuff to things we own

2024-08-20 00:56 UTC, 0xShaito commented on test/integration/arbitrum/CreateRequest.t.sol
> +    bytes32 _requestId = _eboRequestCreator.requestIdPerChainAndEpoch('chainId1', _currentEpoch);
Check that encoding the whole request gives you the same requestId

2024-08-20 16:00 UTC, 0xShaito approved these changes

2024-08-20 18:57 UTC, 0xJabberwock approved these changes

2024-08-20 18:57 UTC, 0xJabberwock commented on src/contracts/EBORequestCreator.sol
> +        _requestModuleData.epoch = _epoch;
Why overwrite the `epoch` field within the `for` loop when it can be written once outside it?

2024-08-20 18:57 UTC, 0xJabberwock commented on test/integration/arbitrum/CreateRequest.t.sol
> +    IEBORequestModule.RequestParameters memory _requestModuleData;
Observation: there are two `RequestParameters` variables—`_requestModuleData` (in `CreateRequest.t.sol`) and `_requestParams` (in `IntegrationBase.sol`).

2024-08-20 18:58 UTC, merged