feat: draft
defi-wonderland/EBO-core pull request #15
Opened 2024-08-20 02:24 UTC by ashitakah

# 🤖 Linear

Closes GRT-17

2024-08-20 11:36 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +  uint256 public immutable MIN_THAWING_PERIOD = 30 days;
Lets set it in the constructor

2024-08-20 11:40 UTC, 0xShaito requested changes

2024-08-20 11:40 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +    IHorizonStaking.Provision memory _provisionData = horizonStaking.getProvision(msg.sender, prophet);
```suggestion
    IHorizonStaking.Provision memory _provisionData = horizonStaking.getProvision(msg.sender, address(this));
```

The verifier will be this contract

2024-08-20 11:40 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +    if (_provisionData.thawingPeriod != MIN_THAWING_PERIOD) revert HorizonAccountingExtension_InvalidThawingPeriod();
Add a todo to review checking the max verifier cut too

2024-08-20 11:40 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +    if (_bondAmount > totalBonded[msg.sender]) revert HorizonAccountingExtension_InsufficientBondedTokens();
This check is not needed as it should never happen. Just let it revert with the -=

2024-08-20 11:40 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +contract HorizonAccountingExtension is IHorizonAccountingExtension {
Use the accounting extension interface

2024-08-20 11:40 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +  address public prophet;
immutable

2024-08-20 11:40 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +  IHorizonStaking public horizonStaking;
immutable

2024-08-20 11:40 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +  }
Missing the slash action

2024-08-26 19:17 UTC, 0xJabberwock requested changes

2024-08-26 19:17 UTC, 0xJabberwock commented on test/unit/HorizonAccountingExtension.t.sol
> +// contract HorizonAccountingExtension_Unit_BondedAction is HorizonAccountingExtension_Unit_BaseTest {
Unit tests for many functions are lacking, but that shouldn't be a burden considering that they could potentially be inherited from Prophet, entirely.

2024-08-30 20:38 UTC, ashitakah commented on src/interfaces/IHorizonAccountingExtension.sol
> +  function approvedModules(address _user) external view returns (address[] memory _approvedModules);
👍

2024-08-30 20:38 UTC, ashitakah commented on test/utils/Helpers.sol
> +    assumeNotPrecompile(_address, block.chainid); // using Optimism chaind id for precompiles filtering
👍

2024-08-30 20:39 UTC, ashitakah commented on test/utils/Helpers.sol
> +  bytes32 internal _mockDisputeId = keccak256(abi.encode(mockDispute));
👍

2024-08-30 20:43 UTC, closed without merging