feat: slashing
defi-wonderland/EBO-core pull request #18
Opened 2024-08-23 22:32 UTC by 0xShaito

# 🤖 Linear

Closes GRT-XXX

2024-08-26 21:39 UTC, ashitakah requested changes

2024-08-26 21:39 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +    pledgerClaimed[_requestId][_pledger] = true;
As you said if we create a mapping with the requestId and the pledger we dont need to accounting the claimAmount

2024-08-26 21:39 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +  function slash(bytes32 _disputeId, uint256 _nUsers) external {
should has any access control?

2024-08-26 21:39 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +  function _slash(bytes32 _disputeId, uint256 _nUsers) internal {
I dont like nUsers as param

2024-08-26 21:39 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +          // What if it's not 100%?
wdym with this comment

2024-08-26 21:39 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +      address _user = _users.at(0);
is that right? You are always taking the same user

2024-08-26 21:39 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +        _slashedUsers++;
unchecked maybe?

2024-08-26 21:39 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +      uint256 _slashAmount = _calculateSlashAmount(_disputeId, _user);
should be named as pledger and not user?

2024-08-26 21:39 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +    EnumerableSet.AddressSet storage _users = _pledgers[_disputeId];
Maybe im missing something but, why we need to pass as param de nUsers to slash?

2024-08-27 12:14 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +  function _slash(bytes32 _disputeId, uint256 _nUsers) internal {
Any other ideas?

2024-08-27 12:16 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +      address _user = _users.at(0);
But I'm removing the elemen from the set

2024-08-27 12:17 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +    EnumerableSet.AddressSet storage _users = _pledgers[_disputeId];
It's just to know how many users to slash

2024-08-30 03:49 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +    GRT.transfer(_pledger, _claimAmount - _totalPledged);
I suggest implementing `SafeERC20` for the token operations.

2024-08-30 03:49 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +    while (_slashedUsers < _nUsers || _users.length() > 0) {
Shouldn't you use the logical AND (`&&`) for the `while` condition?

2024-09-02 14:54 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +    while (_slashedUsers < _nUsers || _users.length() > 0) {
GUT!

2024-09-02 14:55 UTC, closed without merging