feat: horizon accounting extension
defi-wonderland/EBO-core pull request #19
Opened 2024-08-28 16:03 UTC by ashitakah

2024-08-30 03:32 UTC, 0xJabberwock reviewed
This review continues the one I left in https://github.com/defi-wonderland/EBO-core/pull/15, whose comments I didn't repeat here.

Unit tests look complete to me so far! 👏

2024-08-30 03:32 UTC, 0xJabberwock commented on test/unit/HorizonAccountingExtension.t.sol
> +    _provisionData.thawingPeriod = 30 days;
The line `_provisionData;` could be erased here and elsewhere.

2024-08-30 03:32 UTC, 0xJabberwock commented on test/unit/HorizonAccountingExtension.t.sol
> +    horizonAccountingExtension.setPledgedForTest(_disputeId, _amount);
Shouldn't all assumptions already be within `happyPath`?

2024-08-30 03:32 UTC, 0xJabberwock commented on test/unit/HorizonAccountingExtension.t.sol
> +  bytes32 internal _disputeId;
Here and elsewhere, you could leverage the variables that come with `Helpers.sol` instead of declaring new ones for their same purpose.

2024-08-30 03:32 UTC, 0xJabberwock commented on test/unit/HorizonAccountingExtension.t.sol
> +  }
`happyPath` is empty!

2024-08-30 03:32 UTC, 0xJabberwock commented on test/unit/HorizonAccountingExtension.t.sol
> +  }
`happyPath` is empty!

2024-08-30 20:43 UTC, ashitakah commented on test/unit/HorizonAccountingExtension.t.sol
> +  }
until we have the logic coded

2024-08-30 20:43 UTC, ashitakah commented on test/unit/HorizonAccountingExtension.t.sol
> +  }
until we have the logic coded

2024-08-30 20:44 UTC, ashitakah commented on test/unit/HorizonAccountingExtension.t.sol
> +    _provisionData.thawingPeriod = 30 days;
👍

2024-08-30 20:57 UTC, ashitakah commented on test/unit/HorizonAccountingExtension.t.sol
> +    horizonAccountingExtension.setPledgedForTest(_disputeId, _amount);
👍

2024-08-30 22:16 UTC, ashitakah commented on test/unit/HorizonAccountingExtension.t.sol
> +  bytes32 internal _disputeId;
👍

2024-08-30 22:36 UTC, 0xJabberwock commented on test/unit/HorizonAccountingExtension.t.sol
> +  bytes32 internal _disputeId;
You could replace `_dispute` with `mockDispute`.

2024-08-31 16:17 UTC, 0xJabberwock approved these changes

2024-08-31 16:20 UTC, 0xJabberwock requested changes
Lint and merge! 🚀

2024-08-31 19:35 UTC, 0xJabberwock approved these changes

2024-09-02 16:07 UTC, 0xShaito approved these changes

2024-09-02 19:07 UTC, 0xJabberwock approved these changes

2024-09-02 19:11 UTC, merged