feat: deployment script
defi-wonderland/EBO-core pull request #21
Opened 2024-08-29 04:40 UTC by 0xJabberwock

# 🤖 Linear

Closes GRT-138

2024-08-29 20:47 UTC, ashitakah commented on script/Deploy.s.sol
> +    _disputeDisputeWindow = 0;
I think that can be different each field, but also, put the same values could be easiest for the usage

2024-08-31 20:08 UTC, 0xJabberwock commented on test/unit/Deploy.t.sol
> +    // assertEq(address(deploy.eboRequestModule()).code, type(EBORequestModule).runtimeCode);
Asserting the `runtimeCode` of a contract type with the `code` deployed at the expected address effectively checks that the deployed bytecode is the desired one. However, this cannot be done in presence of contracts containing `immutable` variables. 😕

2024-08-31 20:08 UTC, 0xJabberwock commented on script/Deploy.s.sol
> +    // requestData.finalityModuleData = abi.encode(_finalityParams);
I want to confirm that `finalityModuleData` will remain empty for EBO's use cases.

2024-09-02 15:57 UTC, 0xShaito commented on script/Deploy.s.sol
> +    // requestData.finalityModuleData = abi.encode(_finalityParams);
Yes! No data.

2024-09-02 16:04 UTC, 0xShaito requested changes

2024-09-02 16:04 UTC, 0xShaito commented on script/Deploy.s.sol
> +  function _setRequestData(IEBORequestCreator _precomputedEBORequestCreator) internal {
Let's do this as a return of the object and not a set to a variable in storage maybe

2024-09-02 18:02 UTC, 0xJabberwock commented
When inheriting from `BondEscalationModule`, I'm not able to compile due to the cursed import statement that comes with it:
```solidity
// @defi-wonderland/prophet-modules/solidity/contracts/modules/dispute/BondEscalationModule.sol
import 'import {FixedPointMathLib} from 'node_modules/solmate/srcutils/FixedPointMathLib.sol';
```
Strange thing is that the line isn't bugged in `prophet-modules` repo, so most probably the `solidity-exporter-action` is misbehaving.

2024-09-05 13:58 UTC, 0xShaito requested changes

2024-09-05 13:58 UTC, 0xShaito commented on script/Deploy.s.sol
> +    paymentAmount = 0.1 ether;
Lets have paymentAmount be 0 as we don't have that ready yet

2024-09-05 14:39 UTC, 0xShaito approved these changes

2024-09-06 15:19 UTC, ashitakah approved these changes
Really well done !

2024-09-06 15:28 UTC, merged