docs: readme
defi-wonderland/EBO-core pull request #26
Opened 2024-09-06 20:19 UTC by 0xShaito

# 🤖 Linear

Closes GRT-157

2024-09-10 04:33 UTC, 0xJabberwock requested changes

2024-09-10 04:33 UTC, 0xJabberwock commented on README.md
> +cast wallet import $ARBITRUM_DEPLOYER --interactive
`$ARBITRUM_DEPLOYER` needs to be added to `.env.example` and implemented in `yarn deploy:arbitrum`. Also, let's rename it to `$ARBITRUM_DEPLOYER_NAME`.

2024-09-10 04:33 UTC, 0xJabberwock commented on README.md
> +| `yarn test:integration` | Run integration tests.                                     |
There are two setup sections which are more or less redundant. A similar description for all these commands can be found below.

2024-09-11 02:09 UTC, ashitakah requested changes

2024-09-11 02:09 UTC, ashitakah commented on README.md
> +EBO uses [Prophet](https://github.com/defi-wonderland/prophet-core). A versatile and fully adaptable optimistic oracle solution that allows users to set custom modules to achieve the functionality th
do we have a book for prophet instead of use the github link

2024-09-11 02:09 UTC, ashitakah commented on README.md
> +> Only allows one pair of epoch-chainId request to be active at a time.
now the warning makes no sense because the function only allows to pass 1 by 1

2024-09-12 14:11 UTC, 0xShaito commented on README.md
> +> Only allows one pair of epoch-chainId request to be active at a time.
I modified it. If you create a request for a chainId + epoch you can't create the same one in a different call

2024-09-12 18:02 UTC, 0xShaito commented on README.md
> +**AccountingExtension**
Moving to periphery

2024-09-12 18:04 UTC, 0xShaito commented on README.md
> +| `yarn test:integration` | Run integration tests.                                     |
I think it's cool to leave it as a summary easy to see

2024-09-12 18:27 UTC, 0xJabberwock commented on README.md
> +**AccountingExtension**
Contracts under `Periphery` were those that couldn't be found in Prophet's base architecture; hence why I proposed the `Extensions` category.

2024-09-12 18:28 UTC, 0xJabberwock approved these changes
Notice that `EBO_flows.png` contains some inexact naming.

2024-09-12 22:51 UTC, ashitakah approved these changes

2024-09-13 13:27 UTC, merged