feat: remove array
defi-wonderland/EBO-core pull request #27
Opened 2024-09-06 22:19 UTC by ashitakah

2024-09-08 01:40 UTC, 0xShaito commented on src/contracts/EBORequestCreator.sol
> +    _requestId = requestIdPerChainAndEpoch[_chainId][_epoch];
define requestId here directly

2024-09-08 01:41 UTC, 0xShaito commented on src/contracts/EBORequestCreator.sol
> +    _encodedChainId = _encodeChainId(_chainId);
same, define the variable here

2024-09-08 01:41 UTC, 0xShaito commented on src/contracts/EBORequestCreator.sol
> +      _requestId == bytes32(0)
put this in a variable and revert in case it's false

2024-09-10 04:42 UTC, 0xJabberwock requested changes

2024-09-10 04:42 UTC, 0xJabberwock commented on src/interfaces/IEBORequestCreator.sol
> +  function createRequests(uint256 _epoch, string calldata _chainId) external;
Let's rename to `createRequest()`.

2024-09-10 04:42 UTC, 0xJabberwock commented on src/contracts/EBORequestCreator.sol
> +      _requestId = ORACLE.createRequest(_requestData, bytes32(0));
What do you think about returning the `requestId`?

2024-09-11 01:31 UTC, ashitakah commented on src/contracts/EBORequestCreator.sol
> +    _requestId = requestIdPerChainAndEpoch[_chainId][_epoch];
👍

2024-09-11 01:31 UTC, ashitakah commented on src/contracts/EBORequestCreator.sol
> +    _encodedChainId = _encodeChainId(_chainId);
👍

2024-09-11 01:36 UTC, ashitakah commented on src/contracts/EBORequestCreator.sol
> +      _requestId == bytes32(0)
👍

2024-09-11 01:36 UTC, ashitakah commented on src/interfaces/IEBORequestCreator.sol
> +  function createRequests(uint256 _epoch, string calldata _chainId) external;
👍

2024-09-11 01:37 UTC, ashitakah commented on src/contracts/EBORequestCreator.sol
> +      _requestId = ORACLE.createRequest(_requestData, bytes32(0));
It could be however the scripting team told me that is not neccessary, they just need the emit

2024-09-11 02:29 UTC, 0xJabberwock approved these changes

2024-09-11 02:29 UTC, 0xJabberwock commented on test/integration/arbitrum/CreateRequest.t.sol
> -    _eboRequestCreator.createRequest(_currentEpoch, _chainId);
Probably you didn't mean to delete the above.

2024-09-11 20:24 UTC, ashitakah commented on test/integration/arbitrum/CreateRequest.t.sol
> -    _eboRequestCreator.createRequest(_currentEpoch, _chainId);
👍

2024-09-11 22:40 UTC, 0xJabberwock approved these changes

2024-09-12 14:10 UTC, 0xShaito approved these changes

2024-09-12 17:01 UTC, merged