Feat/operators
defi-wonderland/EBO-core pull request #28
Opened 2024-09-09 17:34 UTC by 0xShaito

# 🤖 Linear

Closes GRT-XXX

2024-09-11 16:57 UTC, ashitakah reviewed
I would like to know where the users authorize a valid operator. I guess that have to be in horizon staking. My question here is: Is there any way that another user authorize a malicious operator? Except that, the code looks solid

2024-09-11 16:57 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +    }
I like this one

2024-09-11 16:57 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> -  /// @inheritdoc IHorizonAccountingExtension
why this is deleted?

2024-09-11 17:11 UTC, 0xJabberwock requested changes

2024-09-11 18:56 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> -  /// @inheritdoc IHorizonAccountingExtension
It's only called by the BondEscalationResolutionModule (which we don't use)

2024-09-11 18:56 UTC, 0xShaito commented on src/interfaces/IHorizonAccountingExtension.sol
> -  function releasePledge(
It's only called by the BondEscalationResolutionModule (which we don't use)

2024-09-11 18:59 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
>    mapping(bytes32 _disputeId => EnumerableSet.AddressSet _pledger) internal _pledgers;
The problem is that the amount of pledges it stored in the operators name and not the bonder. To slash the bonder first we need to get the amount of pledges the operator made

2024-09-11 18:59 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +      _slashAmount = _calculateSlashAmount(_pledger, _result, _status);
The pledge is made by the operator so it's stored for them in the BondEscalationModule

2024-09-12 03:58 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +  // [X] 1. Operator can only operate for one bonder at a time
Problem would be that we wouldn't be able to retrieve on behalf of which bonder an operator is acting, unless we modified a bunch of Prophet's interfaces. No easy way out.

2024-09-12 06:06 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
>    mapping(bytes32 _disputeId => EnumerableSet.AddressSet _pledger) internal _pledgers;
Why isn't `BondEscalationAccounting` the one tracking `pledgesForDispute` and `pledgesAgainstDispute` in the first place, instead of `BondEscalationModule`?

```
TODO: To calculate the amount of pledges, we need to check for both the bonder and the operator. How should we do this?
```

The above is my answer. By implementing it, we could get rid of `bonderForRequest`, `bonderForDispute`, and `HorizonAccountingExtension_BonderMismatch`.

2024-09-12 06:37 UTC, 0xJabberwock requested changes

2024-09-12 06:37 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +    // TODO: Validate participants against bonders
Why? The participants registered in the `Oracle` must be the requester, proposer and disputer, who may not be bonders.

2024-10-16 07:42 UTC, closed without merging