feat: arbitrable
defi-wonderland/EBO-core pull request #30
Opened 2024-09-11 22:32 UTC by ashitakah

# 🤖 Linear

Closes GRT-148

2024-09-13 01:53 UTC, 0xJabberwock requested changes
Exquisite PR!

2024-09-13 01:53 UTC, 0xJabberwock commented on test/unit/CouncilArbitrator.t.sol
>      bytes32 indexed _disputeId, IOracle.Request _request, IOracle.Response _response, IOracle.Dispute _dispute
Erase `SetArbitrator` and `SetCouncil` events.

2024-09-13 01:53 UTC, 0xJabberwock commented on src/contracts/Arbitrable.sol
> +contract Arbitrable is IArbitrable {
I think the `@notice` and `@title` should be updated. I propose `ArbitrationHub` for the latter.

2024-09-13 12:56 UTC, 0xShaito commented on src/contracts/Arbitrable.sol
> +  function isValidArbitrator(address _caller) public view {
Would prefer validateArbitrator

2024-09-13 13:00 UTC, 0xShaito commented on test/unit/CouncilArbitrator.t.sol
> +    vm.mockCall(
mockAndExpect pls

2024-09-18 13:58 UTC, ashitakah commented on src/contracts/EBORequestCreator.sol
> +  IArbitrable public immutable ARBITRABLE;
👍

2024-09-18 14:00 UTC, ashitakah commented on test/unit/Arbitrable.t.sol
> +    isValidArbitrator(msg.sender);
👍

2024-09-18 14:02 UTC, ashitakah commented on test/unit/CouncilArbitrator.t.sol
>      bytes32 indexed _disputeId, IOracle.Request _request, IOracle.Response _response, IOracle.Dispute _dispute
👍

2024-09-18 14:14 UTC, ashitakah commented on test/unit/CouncilArbitrator.t.sol
> +    vm.mockCall(
👍

2024-09-18 14:25 UTC, 0xShaito approved these changes

2024-09-18 14:30 UTC, 0xJabberwock approved these changes

2024-09-18 14:39 UTC, merged