feat: integrate `HorizonAccountingExtension`
defi-wonderland/EBO-core pull request #37
Opened 2024-09-23 22:28 UTC by 0xJabberwock

# 🤖 Linear

Closes GRT-185

2024-09-26 08:31 UTC, 0xShaito requested changes

2024-09-26 08:31 UTC, 0xShaito commented on script/Deploy.s.sol
> +    paymentAmount = 0.1 ether;
I think this should still be 0 as we are not paying rewards?f

2024-09-26 08:31 UTC, 0xShaito commented on script/Deploy.s.sol
>      responseDisputeWindow = block.timestamp + 1 weeks;
I'm pretty sure that this value is relative so we don't need to add the timestamp (it's in blocknum)

2024-10-03 20:02 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +      bondSize: _bondEscalationModule.decodeRequestData(_request.disputeModuleData).bondSize,
🙄

2024-10-03 20:02 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +      while (_balance < _rewardAmount) {
🙄

2024-10-03 20:08 UTC, 0xJabberwock reviewed
The `ARBITRUM_RPC` contained in the repo's secrets should change from Arbitrum Mainnet to Arbitrum Sepolia for the integration tests to be run successfully by GitHub Actions.

2024-10-03 20:51 UTC, 0xJabberwock commented on script/Deploy.s.sol
>      responseDisputeWindow = block.timestamp + 1 weeks;
Yes! Nonetheless, it turned out to be convenient to add `block.timestamp` that way at the moment of managing the test environment, which may roll block numbers and warp block timestamps in the same context. All these params must be reviewed after the block-number-to-block-timestamp migration and their proper relativization in Prophet.

2024-10-05 07:12 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +      bondSize: _bondEscalationModule.decodeRequestData(_request.disputeModuleData).bondSize,
Good catch!

2024-10-05 07:41 UTC, 0xShaito reviewed
Looks good!

2024-10-08 06:31 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +        _unbond(_user, _slashAmount);
This should also be added for the pay function right?

2024-10-08 14:38 UTC, 0xShaito approved these changes

2024-10-13 20:10 UTC, ashitakah commented on package.json
> +    "deploy:arbitrum": "bash -c 'source .env && forge script Deploy --rpc-url arbitrum --account $ARBITRUM_DEPLOYER_NAME --broadcast --verify --chain arbitrum -vvvvv'",
Should we have 2. 1 for mainnet and another one for sepolia?

2024-10-13 20:25 UTC, ashitakah requested changes

2024-10-13 20:25 UTC, ashitakah commented on test/integration/arbitrum/BondEscalation.t.sol
>    function test_PledgeForDispute() public {
What if to move those lines to the setup because you need it in all functions:
```
    // Create the request
    bytes32 _requestId = _createRequest();
    // Propose the response
    bytes32 _responseId = _proposeResponse(_requestId);
    // Dispute the response
    bytes32 _disputeId = _disputeResponse(_requestId, _responseId);
```

2024-10-13 20:25 UTC, ashitakah commented on test/integration/arbitrum/DisputeResponse.t.sol
>    function test_DisputeResponse() public {
I had to do it the same, I mean rollback to simulare dispute window over, Could you put a more descriptive comments saying why you roll back the blocks?

2024-10-13 20:25 UTC, ashitakah commented on test/integration/arbitrum/EscalateDispute.t.sol
>    function test_EscalateDispute() public {
Here you are testing when you escalate the dispute first time, after the second escalation with another response and dispute follow another flow. Could be awesome to have it. Also maybe im missing something but could be good yo have the expectCalls about the release and pay etc. Maybe im missing something and you already have it

2024-10-13 20:41 UTC, 0xJabberwock commented on test/integration/arbitrum/BondEscalation.t.sol
>    function test_PledgeForDispute() public {
It proves to be inconvenient because the functions' return values are always needed for the following interactions within the test case's context.

2024-10-15 12:55 UTC, ashitakah commented on test/integration/arbitrum/BondEscalation.t.sol
>    function test_PledgeForDispute() public {
And what if to create the variables, and set it in the setup?

2024-10-15 14:22 UTC, 0xShaito commented on package.json
> +    "deploy:arbitrum": "bash -c 'source .env && forge script Deploy --rpc-url arbitrum --account $ARBITRUM_DEPLOYER_NAME --broadcast --verify --chain arbitrum -vvvvv'",
Lets keep it like this for now as we will change it in the future

2024-10-15 14:39 UTC, 0xJabberwock commented on test/integration/arbitrum/BondEscalation.t.sol
>    function test_PledgeForDispute() public {
That's an alternative, although you wouldn't know whether the variables have been written or not without checking the setup.

2024-10-16 13:55 UTC, 0xShaito approved these changes

2024-10-16 14:04 UTC, ashitakah approved these changes

2024-10-16 14:07 UTC, merged