docs: add rewards warning
defi-wonderland/EBO-core pull request #41
Opened 2024-10-07 09:55 UTC by 0xShaito

# 🤖 Linear

Closes GRT-207

2024-10-07 14:47 UTC, 0xJabberwock requested changes

2024-10-07 14:47 UTC, 0xJabberwock commented on src/interfaces/IHorizonAccountingExtension.sol
> +   *    Rewards should be claimed before that period ends to ensure that funds are available.
A similar `@dev` note should be added to `slash()`.

2024-10-07 16:52 UTC, ashitakah requested changes

2024-10-07 16:52 UTC, ashitakah commented on README.md
> +> Rewards from dispute escalations should be claimed before that period ends to ensure that funds are available.
+1

2024-10-13 20:01 UTC, ashitakah approved these changes

2024-10-13 20:25 UTC, 0xJabberwock submitted a review, later dismissed

2024-10-15 15:00 UTC, 0xJabberwock approved these changes

2024-10-15 15:00 UTC, 0xJabberwock commented on src/interfaces/IHorizonAccountingExtension.sol
> +   * @notice Allows a anyone to slash a number of users for a dispute
I support mentioning that slashing only applies to those pledgers who have lost.

2024-10-16 14:09 UTC, merged