test: finalize request integration
defi-wonderland/EBO-core pull request #43
Opened 2024-10-10 16:27 UTC by 0xJabberwock

# 🤖 Linear

Closes GRT-116

2024-10-11 06:31 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    vm.expectRevert(IBondedResponseModule.BondedResponseModule_TooEarlyToFinalize.selector);
Can we have another test for this so we don't copy paste it in all of the cases?

2024-10-11 06:33 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    // _finalizeRequest(_requestId, 0);
Because the respone was disputed right? Is this expected?

2024-10-11 06:35 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    _arbitrateDispute(_disputeId, IOracle.DisputeStatus.Won);
Can we add an assert here to make sure it finalized?

2024-10-11 06:35 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    _arbitrateDispute(_disputeId, IOracle.DisputeStatus.Lost);
Same

2024-10-11 06:43 UTC, 0xShaito requested changes

2024-10-11 06:43 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    _arbitrateDispute(_disputeId, IOracle.DisputeStatus.Won);
I know we have the reverts below but I think it would be more expresive to make sure that it was indeed finalized without a response

2024-10-11 06:43 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    _arbitrateDispute(_disputeId, IOracle.DisputeStatus.NoResolution);
Same

2024-10-11 06:43 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    // TODO: What if the request is finalized without response, after a response has been disputed but before
wdym? I guess it goes through the flow of escalation any ways right?

2024-10-11 06:43 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    vm.skip(true); // TODO: How does the proposer release the response bond?
Remove the todo? Or is it not the release below?

2024-10-11 06:43 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    // TODO: What if the release does not revert because the proposer had bonded multiple times for the same request?
How could they bond multiple times for the same request?

The bond function used for this has a mapping `bondedAmountOf[_bonder][_token][_requestId]` and this would revert in case they try to release again no?

2024-10-11 17:45 UTC, 0xJabberwock commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    // _finalizeRequest(_requestId, 0);
Yes, because the unique available response was disputed. I left the `TODO` to confirm if that's the expected behaviour, and it seems so.

2024-10-11 17:51 UTC, 0xJabberwock commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    // TODO: What if the request is finalized without response, after a response has been disputed but before
Yes, it goes through the escalation process successfully. However, then it doesn't seem possible to release the unfinalizable response bond, which is the test case's meaning. Take this `TODO` as an introductory context for the one below.

2024-10-11 17:57 UTC, 0xJabberwock commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    vm.skip(true); // TODO: How does the proposer release the response bond?
The test case is skipped there because it fails otherwise with the line below, despite it being correctly written.

2024-10-11 18:08 UTC, 0xJabberwock commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    // TODO: What if the release does not revert because the proposer had bonded multiple times for the same request?
A proposer could bond multiple times for the same request by proposing another response or disputing one. In such cases, he could leverage his unfinalizable response to keep subtracting from `bondedAmountOf` without reverting, and then withdraw his response and/or dispute bonds for that request.

2024-10-14 06:33 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    vm.skip(true); // TODO: How does the proposer release the response bond?
Interesting. We will take a look at it from our side! Can you create a task in linear?

2024-10-14 06:34 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    // TODO: What if the release does not revert because the proposer had bonded multiple times for the same request?
This is a good catch. Do you think this could lead to an issue anywhere?

2024-10-14 19:33 UTC, 0xJabberwock commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    // TODO: What if the release does not revert because the proposer had bonded multiple times for the same request?
Of course. A disputed proposer could mock the system so not to pay his response bond of a certain request to the disputer by means of transaction reversion, making it impossible to settle a bond escalation or resolve a dispute in which he lost; he could withdraw the disputed bond too.

If I'm not mistaken, the hack might be prevented depending on the celerity of the arbitrator and the combination of time constraints derived from the modules' params.

2024-10-14 19:46 UTC, 0xJabberwock commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    vm.skip(true); // TODO: How does the proposer release the response bond?
Done: [OPO-665](https://linear.app/defi-wonderland/issue/OPO-665/release-unfinalizable-response-bonds-after-request-is-finalized).

2024-10-17 14:22 UTC, 0xJabberwock commented on test/integration/arbitrum/ArbitrateDispute.t.sol
> +    assertEq(horizonAccountingExtension.totalBonded(_proposer), 0);
The assertions to `Oracle::finalize` and the subsequent `HorizonAccountingExtension::release`, if any, are redundant with the ones found in `FinalizeRequest.t.sol`.

2024-10-17 14:36 UTC, ashitakah requested changes

2024-10-21 14:56 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> +    vm.warp(_responseCreatedAt + responseDisputeWindow - responseDeadline);
True!

2024-10-21 16:07 UTC, 0xJabberwock reviewed
Unskip tests and update `TODO` notes.

2024-10-21 16:07 UTC, 0xJabberwock commented on test/integration/arbitrum/FinalizeRequest.t.sol
> -    vm.warp(_requestCreatedAt + responseDeadline);
Why delete this warp in specific? The other test cases kept it.

2024-10-21 16:47 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> -    vm.warp(_requestCreatedAt + responseDeadline);
Because we do it at the start (line 225)

2024-10-21 17:24 UTC, 0xShaito commented on test/integration/arbitrum/FinalizeRequest.t.sol
> -    vm.warp(_requestCreatedAt + responseDeadline);
Sorry, you are right!

I can safely remove this because this error comes first. There are other cases that I added now

2024-10-23 06:44 UTC, 0xShaito approved these changes

2024-10-23 13:28 UTC, ashitakah approved these changes

2024-10-23 13:29 UTC, merged