fix: thawing tokens
defi-wonderland/EBO-core pull request #44
Opened 2024-10-11 06:44 UTC by 0xShaito

# 🤖 Linear

Closes GRT-XXX

2024-10-11 16:58 UTC, 0xJabberwock requested changes
Looking good!

2024-10-11 16:58 UTC, 0xJabberwock commented on test/integration/arbitrum/IntegrationBase.sol
> +  function _createRequest(string memory _customChainId) internal returns (bytes32 _requestId) {
You could let it input a `_customEpoch`.

2024-10-11 16:58 UTC, 0xJabberwock commented on test/integration/arbitrum/IntegrationBase.sol
I suggest replacing `currentNonce++` with a call to `Oracle::totalRequestCount`.

2024-10-11 16:58 UTC, 0xJabberwock commented on test/integration/arbitrum/IntegrationBase.sol
> +  uint96 public currentNonce;
I purposely made all variables within `IntegrationBase` `internal` so they could be easily differentiated from the `public` ones inherited from `Deploy` (which account for all its variables).

2024-10-11 16:58 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +    if (_amount > _availableTokens) revert HorizonAccountingExtension_InsufficientTokens();
Hmm, I can't come up with a reason why `tokensThawing` would ever be greater than `tokens`, other than rounding issues.

2024-10-11 16:58 UTC, 0xJabberwock commented on test/integration/arbitrum/HorizonAccountingExtension.t.sol
> +pragma solidity 0.8.26;
License identifier should be `GPL-3.0` as per #42.

2024-10-11 16:58 UTC, 0xJabberwock commented on test/integration/arbitrum/HorizonAccountingExtension.t.sol
> +    vm.roll(block.number + 1);
Why?

2024-10-11 16:58 UTC, 0xJabberwock commented on test/integration/arbitrum/HorizonAccountingExtension.t.sol
> +    horizonStaking.thaw(_proposer, address(horizonAccountingExtension), responseBondSize + 1);
You may add `_thaw()` in `IntegrationBase`.

2024-10-11 16:58 UTC, 0xJabberwock commented on test/integration/arbitrum/HorizonAccountingExtension.t.sol
> +    vm.warp(responseDeadline - 1);
There hasn't been another `warp` since the last one, which equals this one. Moreover, you could avoid warping at all.

2024-10-14 08:29 UTC, 0xShaito commented on test/integration/arbitrum/HorizonAccountingExtension.t.sol
> +    vm.roll(block.number + 1);
Just copy paste. Not needed!

2024-10-14 19:04 UTC, ashitakah requested changes

2024-10-14 19:04 UTC, ashitakah commented on src/contracts/HorizonAccountingExtension.sol
> +    if (totalBonded[_bonder] > _provisionData.tokens) {
It has any chance to happen? With the last logic we had to do it for the tokens thawing but now, with the first check, Im not sure if is necessary.

2024-10-14 19:04 UTC, ashitakah commented on test/integration/arbitrum/BondEscalation.t.sol
> +    _addToProvision(_pledgerAgainst, _tokensToThaw);
+ 1

2024-10-14 19:04 UTC, ashitakah commented on test/integration/arbitrum/BondEscalation.t.sol
>      vm.warp(disputeDeadline);
I cant find the inssuficientBondedTokens error in the test

2024-10-15 07:47 UTC, 0xShaito commented on test/integration/arbitrum/BondEscalation.t.sol
> +    _thaw(_pledgerFor, _tokensToThaw);
No because they have maxNumber * bondSize provisioned. To do 1 pledge they need bondSize so we need to remove up to (bondSize - 1) for it to fail

2024-10-15 07:49 UTC, 0xShaito commented on test/integration/arbitrum/BondEscalation.t.sol
> +    _addToProvision(_pledgerFor, _tokensToThaw);
reprovision is different. It changes the verifier and thaws tokens. addToProvision is the correct one to just add tokens to the existing one

2024-10-15 08:28 UTC, 0xShaito commented on test/integration/arbitrum/BondEscalation.t.sol
>      vm.warp(disputeDeadline);
Added one!

2024-10-15 14:51 UTC, 0xJabberwock approved these changes

2024-10-17 14:24 UTC, 0xJabberwock commented on test/unit/HorizonAccountingExtension.t.sol
> -  ) public {
Why remove it?

2024-10-17 14:32 UTC, ashitakah approved these changes

2024-10-17 14:43 UTC, 0xShaito commented on test/unit/HorizonAccountingExtension.t.sol
> -  ) public {
Added back. I think there was an error in the merge

2024-10-17 14:46 UTC, 0xJabberwock approved these changes

2024-10-17 15:05 UTC, ashitakah approved these changes

2024-10-17 15:32 UTC, 0xJabberwock approved these changes

2024-10-17 16:03 UTC, merged