feat: add data in event
defi-wonderland/EBO-core pull request #45
Opened 2024-10-13 20:00 UTC by ashitakah

Change requested by the offchain team.

Added all data in the request creation event

2024-10-13 20:58 UTC, 0xJabberwock requested changes

2024-10-13 20:58 UTC, 0xJabberwock commented on src/interfaces/IEBORequestCreator.sol
> +    bytes32 _requestId, IOracle.Request indexed _request, uint256 indexed _epoch, string indexed _chainId
I'd argue that `_requestId` should remain `indexed`: since event topics can only hold a single word (32 bytes), the `_request` would get hashed.

2024-10-13 21:05 UTC, ashitakah commented on src/interfaces/IEBORequestCreator.sol
> +    bytes32 _requestId, IOracle.Request indexed _request, uint256 indexed _epoch, string indexed _chainId
I did this, because inside request you have the requestId, and you only can have 3 indexed params so, I didnt know it the bytes32 thing. 👍

2024-10-14 06:30 UTC, 0xShaito commented on src/interfaces/IEBORequestCreator.sol
> +    bytes32 _requestId, IOracle.Request indexed _request, uint256 indexed _epoch, string indexed _chainId
I think it would be better to index by id

2024-10-14 06:30 UTC, 0xShaito submitted a review, later dismissed

2024-10-15 15:01 UTC, 0xJabberwock approved these changes

2024-10-17 06:03 UTC, merged