feat: slashed balance accounting
defi-wonderland/EBO-core pull request #46
Opened 2024-10-14 13:04 UTC by 0xShaito

# 🤖 Linear

Closes GRT-209

2024-10-14 18:31 UTC, ashitakah submitted a review, later dismissed

2024-10-14 18:48 UTC, 0xJabberwock requested changes

2024-10-14 18:48 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +        _slash(_disputeId, 1, MAX_USERS_TO_CHECK, _result, _status);
Should be `while (disputeBalance[_disputeId] < _rewardAmount)`.

2024-10-14 18:48 UTC, 0xJabberwock commented on src/contracts/HorizonAccountingExtension.sol
> +  mapping(bytes32 _disputeId => uint256 _balance) public disputeBalance;
I suggest adding `disputeBalance` assertions to integration tests that call `HorizonAccountingExtension::claimEscalationReward`.

2024-10-15 07:44 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +        _slash(_disputeId, 1, MAX_USERS_TO_CHECK, _result, _status);
Yes. But this change is in your PR. Didn't want to introduce new changes unrelated to this one

2024-10-15 08:35 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +  mapping(bytes32 _disputeId => uint256 _balance) public disputeBalance;
Yes, will be added but now we only have the bondEscalation

2024-10-15 08:36 UTC, 0xShaito commented on src/contracts/HorizonAccountingExtension.sol
> +  mapping(bytes32 _disputeId => uint256 _balance) public disputeBalance;
Created a task for it! https://linear.app/defi-wonderland/issue/GRT-213/integration-testing-for-disputebalance-in-horizonaccountingextension

2024-10-15 14:54 UTC, 0xJabberwock submitted a review, later dismissed

2024-10-17 14:17 UTC, 0xJabberwock commented on src/interfaces/IHorizonAccountingExtension.sol
> -  function authorizedCallers(address _caller) external returns (bool _authorized);
Why remove this from the interface?

2024-10-17 14:42 UTC, 0xShaito commented on src/interfaces/IHorizonAccountingExtension.sol
> -  function authorizedCallers(address _caller) external returns (bool _authorized);
It was duplicated in the interface

2024-10-17 14:45 UTC, 0xJabberwock approved these changes

2024-10-17 14:48 UTC, ashitakah approved these changes

2024-10-17 14:48 UTC, merged