feat: Operato Access Module
defi-wonderland/EBO-core pull request #52
Opened 2024-11-12 14:01 UTC by xorsal

# 🤖 Linear

Closes GRT-227

2024-11-12 17:58 UTC, 0xJabberwock requested changes

2024-11-12 17:58 UTC, 0xJabberwock commented on src/interfaces/IEBOAccessModule.sol
> +  function hasAccess(bytes calldata _data) external view returns (bool _hasAccess);
Is it needed to redeclare `hasAccess()` after having inherited `IAccessModule`?

2024-11-12 17:58 UTC, 0xJabberwock commented on src/interfaces/IEBOAccessModule.sol
> +    returns (IAccessModule.AccessControlParameters memory _params);
The decoding function, featured in many other modules, could, in the case of access modules, be declared in the general `prophet-core` interface (i.e., `IAccessModule`), as the parameters to decode (i.e., `AccessControlParameters`) have already been defined there.

Nevertheless, a second decoding function may lie within the scope and be specific to each access module implementation: `decodeAccessControlData()`, for `AccessControl.data` at least. (Naming is on the edge 🙃)

2024-11-12 17:58 UTC, 0xJabberwock commented on src/contracts/EBOAccessModule.sol
> +// TODO: CHECK IF IS A MODULE, ACCESSCONTROLLER OR SOMETHING ELSE
🤨

2024-11-12 17:58 UTC, 0xJabberwock commented on src/contracts/EBOAccessModule.sol
> +  IHorizonStaking public horizonStaking;
`HorizonAccountingExtension` features an immutable state variable for `HorizonStaking`, which is inconsistent with how it is treated here.

2024-11-12 17:58 UTC, 0xJabberwock commented on src/contracts/EBOAccessModule.sol
> +      horizonStaking.isAuthorized(_params.accessControl.user, address(horizonAccountingExtension), _params.sender);
Given the declaration of `isAuthorized()` in `IHorizonStaking`:
- the `operator` should be the `AccessControlParameters.sender`, which might not be the `AccessControl.user` nor the `msg.sender` in this context;
- the `serviceProvider` should be the `AccessControl.user`, on whose behalf the operator acts;
- the `verifier` should be the `HorizonAccountingExtension`, which is the one able to slash provisions.

2024-11-12 18:27 UTC, xorsal commented on src/contracts/EBOAccessModule.sol
> +      horizonStaking.isAuthorized(_params.accessControl.user, address(horizonAccountingExtension), _params.sender);
I'm glad you saw this! Looks like there has been update on `isAuthorized` parameters order in [`IHorizonStakingMain.sol`](https://github.com/graphprotocol/contracts/pull/944/files#diff-9b7f71192a5d28d6826ebdafc68cd699db1081581d7d87502781dbf7195e8fbeR957)

PR with changes: https://github.com/graphprotocol/contracts/pull/1034/files#diff-32a1336e4cc247ecfc33ebdfcd0f9e2f7bae2c2ec88c6d98a0e149a0533749c7R524-R528

new defined interface:
```
    function isAuthorized(
        address serviceProvider,
        address verifier,
        address operator
    ) 
```

Given this change in the interface I think it's okay, unless I'm not seeing something.

2024-11-13 19:47 UTC, xorsal commented on src/contracts/EBOAccessModule.sol
> +  IHorizonStaking public horizonStaking;
I wasn’t aware of `IHorizonStakingExtension::HORIZON_STAKING()`. I wouldn't say it's inconsistent, it could definitely lead to unexpected behavior if the wrong addresses are set during deployment.

But more importantly, if `horizonStaking` can be obtained via a call (`staticcall`?) to `horizonAccountingExtension`, then I propose removing the `horizonStaking` state variable and instead calling `HorizonStakingExtension::HORIZON_STAKING` every time it’s needed, which is only inside of the `hasAccess` function.

Would this make sense to you?

2024-11-13 20:05 UTC, xorsal commented on src/interfaces/IEBOAccessModule.sol
> +    returns (IAccessModule.AccessControlParameters memory _params);
Agree.

Just a small comment for future reference: we should have started development of this feature in `EBO-core` and moved the requirements up to `prophet-core`.
With the current development/design approach, we receive changes from upstream, attempt to implement them, then realize adjustments are needed upstream, and the cycle repeats.

2024-11-13 21:10 UTC, 0xJabberwock commented on src/contracts/EBOAccessModule.sol
> +  IHorizonStaking public horizonStaking;
Performing an external call ad infinitum to get an immutable variable doesn't make sense to me in terms of gas efficiency, compared to storing it once. The `HorizonStaking` address could be sent in the constructor or got through a single external call in it—however, this last option requires `HorizonAccountingExtension` to have been deployed, which might not be desirable.

Beware that `HorizonStaking`, `HorizonStakingExtension` and `HorizonAccountingExtension` refer to different contracts.

2024-11-14 12:11 UTC, xorsal commented on src/contracts/EBOAccessModule.sol
> +  IHorizonStaking public horizonStaking;
>Beware that HorizonStaking, HorizonStakingExtension and HorizonAccountingExtension refer to different contracts.

My bad, I mixed up the contract names.

`HorizonAccountingExtension` is the one that has the external view `HORIZON_STAKING`

>however, this last option requires HorizonAccountingExtension to have been deployed, which might not be desirable.

The HorizonAccountingExtension should be already deployed when `EBOAccessModule` is live because it's used in `hasAccess` to do the [`isAuthorized` call](https://github.com/defi-wonderland/EBO-core/pull/52/files#diff-5cba60d6f2841fe6c0a4ad8b160c3d6cec655ddcd33a97c22cae493c58243f3dR55).

And if that isn't the case, the module also have `setHorizonAccountingExtension` to update its address whenever necessary.

2024-11-18 15:06 UTC, xorsal commented on src/contracts/EBOAccessModule.sol
> +  IHorizonStaking public horizonStaking;
now whenever the `horizonAccountingExtension` is updated, it will also call `HORIZON_STAKING` and update the `horizonStaking` address.

Major changes in: 630ce61e6fe8247a00697810ba6ff12581f205b7

2024-11-18 15:49 UTC, 0xJabberwock approved these changes

2024-11-18 16:10 UTC, merged