feat: allow to duplicate request id
defi-wonderland/EBO-core pull request #9
Opened 2024-08-15 14:39 UTC by ashitakah

# 🤖 Linear

Closes GRT-78

2024-08-15 16:11 UTC, 0xShaito submitted a review, later dismissed

2024-08-15 18:01 UTC, 0xJabberwock requested changes

2024-08-15 21:33 UTC, ashitakah commented on test/unit/EBORequestCreator.t.sol
> +  function test_emitCreateRequestWithNoResponse(
👍

2024-08-15 21:33 UTC, ashitakah commented on test/unit/EBORequestCreator.t.sol
> +  function test_expectNotEmitRequestIdExistsBlockNumber(
Okey I like it, I include those things in the tests.

2024-08-15 21:40 UTC, ashitakah commented on test/unit/EBORequestCreator.t.sol
> +  function test_expectNotEmitRequestIdExistsBlockNumber(
To give you context, the requestId has to exists but the user wont be able to create a new one if is not finalized, so I test that the requestId is the same and is not creating another one.

2024-08-16 00:14 UTC, 0xShaito approved these changes

2024-08-16 01:41 UTC, 0xJabberwock approved these changes

2024-08-16 01:42 UTC, merged